/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Click at the given screen coordinates. */
export declare function click(x: number, y: number): void
/** Right-click at the given screen coordinates. */
export declare function rightClick(x: number, y: number): void
/** Double-click at the given screen coordinates. */
export declare function doubleClick(x: number, y: number): void
/** Move the mouse cursor to absolute screen position. */
export declare function moveMouse(x: number, y: number): void
/** Drag from one position to another (left button). */
export declare function drag(fromX: number, fromY: number, toX: number, toY: number): void
/** Scroll at the current cursor position. */
export declare function scroll(deltaX: number, deltaY: number): void
/** Type text naturally, character by character. Handles unicode/emoji. */
export declare function typeText(text: string): void
/** Press a single key (e.g., "enter", "tab", "escape", "backspace", "space", "f1"–"f12"). */
export declare function keyPress(key: string): void
/** Press a key combination (e.g., ["cmd", "c"] for copy, ["cmd", "shift", "s"] for save-as). */
export declare function keyCombo(keys: Array<string>): void
/** Information about a display. */
export interface DisplayInfo {
  id: number
  x: number
  y: number
  width: number
  height: number
  isMain: boolean
}
/** Pixel color at a coordinate. */
export interface PixelColor {
  r: number
  g: number
  b: number
  a: number
}
/** Get the number of active displays. */
export declare function getDisplayCount(): number
/** Get bounds information for all active displays. */
export declare function getDisplayBounds(): Array<DisplayInfo>
/** Capture the full screen at the given display (0 = main) and return a JPEG buffer (fast). */
export declare function captureScreen(displayIndex?: number | undefined | null): Buffer
/** Capture a specific region of the screen and return a JPEG buffer. */
export declare function captureRegion(x: number, y: number, w: number, h: number): Buffer
/** Get the pixel color at the given screen position. */
export declare function getPixelColor(x: number, y: number): PixelColor
/** Information about a visible window. */
export interface WindowInfo {
  pid: number
  appName: string
  title: string
  x: number
  y: number
  width: number
  height: number
  layer: number
  isOnScreen: boolean
}
/** List all visible windows on screen with their app name, title, and bounds. */
export declare function listWindows(): Array<WindowInfo>
/** Get the name of the frontmost (active) application. */
export declare function getFrontmostApp(): string
/** Get the PID of the frontmost (active) application. */
export declare function getFrontmostAppPid(): number
/** Activate (bring to front) an application by name. */
export declare function activateApp(name: string): void
/** System information. */
export interface SystemInfo {
  cpuBrand: string
  cpuCount: number
  memTotalMb: number
  memUsedMb: number
  osVersion: string
  hostname: string
}
/** Read the current clipboard text content. */
export declare function clipboardRead(): string
/** Write text to the system clipboard. */
export declare function clipboardWrite(text: string): void
/** Show a native macOS notification. */
export declare function notify(title: string, body: string): void
/** Get system information (CPU, RAM, OS version). */
export declare function getSystemInfo(): SystemInfo
/** Execute a shell command with optional timeout and return stdout + stderr + exit code. */
export interface ExecResult {
  stdout: string
  stderr: string
  code: number
}
export declare function execCommand(cmd: string, timeoutMs?: number | undefined | null): ExecResult
export interface AxElement {
  role: string
  title: string
  description: string
  x: number
  y: number
  width: number
  height: number
}
export declare function isAccessibilityTrusted(): boolean
export declare function listUiElements(pid: number, maxDepth: number): Array<AxElement>
